# Generated by Django 6.0.3 on 2026-04-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_image_car_plate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='image',
            new_name='photo',
        ),
    ]
