# Generated by Django 6.0.3 on 2026-04-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcycle',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='motorcycle/'),
        ),
    ]
