# Generated by Django 6.0.3 on 2026-04-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0002_alter_motorcycle_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorcycle_count', models.IntegerField()),
                ('motorcycle_value', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
