# Generated by Django 6.0.3 on 2026-04-14 00:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motorcycle', '0004_alter_motorcycle_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motorcycle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Moto', 'verbose_name_plural': 'Motos'},
        ),
        migrations.AlterModelOptions(
            name='motorcyclebrand',
            options={'ordering': ['name'], 'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='motorcycleinventory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inventário', 'verbose_name_plural': 'Inventários'},
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='value',
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='fipe_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='fuel',
            field=models.CharField(blank=True, choices=[('gasolina', 'Gasolina'), ('etanol', 'Etanol'), ('flex', 'Flex'), ('eletrico', 'Elétrico')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='ipva_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='licensed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Quilometragem em km', null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='single_owner',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('vendido', 'Vendido'), ('reservado', 'Reservado'), ('manutencao', 'Em manutenção')], default='disponivel', max_length=20),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('automatico', 'Automático'), ('semi_automatico', 'Semi-automático')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motorcycles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='version',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motorcycles', to='motorcycle.motorcyclebrand'),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='engine_cc',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='factory_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='model',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='model_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motorcycleinventory',
            name='motorcycle_value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
