# Generated by Django 6.0.3 on 2026-04-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, choices=[('hatch', 'Hatch'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('pickup', 'Caminhonete'), ('utility', 'Utilitário'), ('station_wagon', 'Station Wagon')], max_length=20, null=True),
        ),
    ]
